// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class SadPandaDb : DataConnection
	{
		public SadPandaDb()
		{
			InitDataContext();
		}

		public SadPandaDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public SadPandaDb(DataOptions<SadPandaDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Gallery> Galleries => this.GetTable<Gallery>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static Gallery? Find(this ITable<Gallery> table, long gid)
		{
			return table.FirstOrDefault(e => e.Gid == gid);
		}

		public static Task<Gallery?> FindAsync(this ITable<Gallery> table, long gid, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Gid == gid, cancellationToken);
		}
		#endregion
	}
}
