// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("unnamed")]
	public class NGallery
	{
		[Column("key"  , CanBeNull = false, IsPrimaryKey = true)] public string  Key   { get; set; } = null!; // text(max)
		[Column("value"                                        )] public string? Value { get; set; } // blob
	}
}
