// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class NHentaiDb : DataConnection
	{
		public NHentaiDb()
		{
			InitDataContext();
		}

		public NHentaiDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public NHentaiDb(DataOptions<NHentaiDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<NGallery> Galleries => this.GetTable<NGallery>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static NGallery? Find(this ITable<NGallery> table, string key)
		{
			return table.FirstOrDefault(e => e.Key == key);
		}

		public static Task<NGallery?> FindAsync(this ITable<NGallery> table, string key, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Key == key, cancellationToken);
		}
		#endregion
	}
}
